const variables = {
	// ORDER STATUS
	STATUS_NEW : 1,
	STATUS_CHECKING : 5,
	STATUS_ATTACHING : 6,
	STATUS_PREPARING : 10,
	STATUS_PREPARE_REJECTED : 11,
	STATUS_PREPARE_COMPLETED : 12,
	STATUS_COMING_YOU : 15,
	STATUS_AWAITING_YOU : 16,
	STATUS_RESERVED : 17,
	STATUS_COMPLETED : 20,
	STATUS_REJECTED : 30,
	// ORDER TYPES
	TYPE_TAKEAWAY : 1,
	TYPE_ON_TABLE : 2,
	TYPE_DELIVERY : 3,
	TYPE_BOOKING : 4,
	// ORDER ACTIONS
	ACTION_BOOKING_EXPIRED: 1,
	ACTION_TAKEAWAY_EXPIRED : 2,
};

export default variables;
